; Doorstep Windows installer (Inno Setup 7).
;
; Stage the release build (doorstep.exe, its DLLs and the data folder) into
; StagingDir, then run this script. Both paths can be overridden from the
; command line, e.g. ISCC.exe /DStagingDir=build\windows\x64\runner\Release

#ifndef MyAppVersion
  #define MyAppVersion "1.1.0"
#endif
#ifndef MyAppName
  #define MyAppName "Doorstep"
#endif
#ifndef StagingDir
  #define StagingDir "D:\inno"
#endif
#ifndef OutputDir
  #define OutputDir "D:\inno-result"
#endif

#define MyAppPublisher "cydercoder"
#define MyAppURL "https://github.com/javex-12/Doorstep"
#define MyAppExeName "doorstep.exe"
#ifndef MySetupIcon
  #define MySetupIcon StagingDir + "\logo.ico"
#endif
; Branded wizard artwork. Generated by
; `dart run tool/generate_installer_wizard.dart` in app/ and copied into the
; staging folder next to doorstep.exe.
#ifndef MyWizardImage
  #define MyWizardImage StagingDir + "\wizard.bmp"
#endif
#ifndef MyWizardSmallImage
  #define MyWizardSmallImage StagingDir + "\wizard-small.bmp"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{00809252-FEC6-448E-83B4-E7F55AE7E47D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#OutputDir}
OutputBaseFilename=Doorstep-{#MyAppVersion}-Setup
SetupIconFile={#MySetupIcon}
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Doorstep artwork instead of the stock Inno wizard.
WizardImageFile={#MyWizardImage}
WizardImageStretch=no
WizardSmallImageFile={#MyWizardSmallImage}
; Signing is optional: pass /DSign to ISCC.exe once a code-signing tool is
; configured, and the installer is signed with it. Unsigned builds omit this
; so the script compiles on any machine.
#ifdef Sign
SignTool=MySignTool
#endif
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible

[Languages]
; The installer is English-only on purpose: not every Inno Setup install ships
; the full Languages\ folder, and the app itself is already translated in 50+
; languages. Add more lines here if the matching .isl files are available.
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"
Name: "chinesesimplified"; MessagesFile: "..\build\windows\inno\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#StagingDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#StagingDir}\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#StagingDir}\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}";
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
